image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      dotnet dev-certs https 
      dotnet restore
      dotnet build
      dotnet tool update --global dotnet-ef
      export PATH="$PATH:/home/gitpod/.dotnet/tools"
      dotnet ef database update

vscode:
  extensions:
    - muhammad-sammy.csharp
